### ISSUE TITLE
Adapter blocks itself randomly

### ISSUE THREAD

**Issue by siduck76** [loh-tar/wpa-cute#10]
This happens very rarely , the wifi adapter blocks itself and I have to run rfkill unblock wlan to fix it up
![2021-01-14-190857_1366x768_scrot](https://user-images.githubusercontent.com/59060246/104600502-16f6e480-569f-11eb-9de9-f093c7254ddc.png).
 My wifi keeps disconnecting sometimes for some seconds and then reconnects itself , any idea what could cause this issue?

**Comment by loh-tar** [comment]
Um, I guess these adapter blocking is not related to wpaCute, not even wpa_suplicant. I think it's some general setup stuff. My bluetooth adapter has from time to time a similar problem, it's disabled after wake-up and I have to enable it. 

These disconnect/reconnect trouble is here too, sometimes. But that should also not related to wpaCute. I think it's also general setup stuff, but of the router. Which channel and so on is used.

**Comment by siduck76** [comment]
seems like it
