### ISSUE TITLE
Where does wpa-cute store configuration files?

### ISSUE THREAD

**Issue by cosmojg** [loh-tar/wpa-cute#5]
I've configured a few networks with wpa-cute, but I don't see any configuration files in /etc/wpa_supplicant. Where does wpa-cute store configuration files for configured networks?

**Comment by loh-tar** [comment]
When your path is right, you may need to save your config. From man page EDIT NETWORK section:

> When  you  add,  delete or modify a network are these changes only made 
> in a temporary manner inside the running wpa_supplicant. They take  
> effect as long as the wpa_supplicant is not terminated or triggered to 
> reload its configuration. You have to save the changes explicit. This is 
> different from the original wpa_gui.

wpaCute itself as no own config file...iirc :-)

**Comment by cosmojg** [comment]
Ah, so it doesn't store anything. How do I explicitly save the changes myself, then?

**Comment by loh-tar** [comment]
`Menu->WPA->Save Config` should do it

**Comment by cosmojg** [comment]
@loh-tar That does the trick! Thanks!
