### ISSUE TITLE
I cannot compile from source your code,

### ISSUE THREAD

**Issue by FrostKnight** [loh-tar/wpa-cute#6]
qt5-make works, but when I go to make, this error comes out:

make -f Makefile.Release
make[1]: Entering directory '~/Downloads/wpa-cute-0.7.1/src'
/usr/bin/uic wpagui.ui -o .ui/ui_wpagui.h
/usr/bin/uic eventhistory.ui -o .ui/ui_eventhistory.h
/usr/bin/uic scanresults.ui -o .ui/ui_scanresults.h
/usr/bin/uic wpsdialog.ui -o .ui/ui_wpsdialog.h
/usr/bin/uic networkconfig.ui -o .ui/ui_networkconfig.h
/usr/bin/uic peers.ui -o .ui/ui_peers.h
/usr/bin/uic about.ui -o .ui/ui_about.h
gcc -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DCONFIG_CTRL_IFACE -DCONFIG_CTRL_IFACE_UNIX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I.. -I../wpa_supplicant/src -I../wpa_supplicant/src/utils -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I.moc -isystem /usr/include/libdrm -I.ui -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/os_unix.o ../wpa_supplicant/src/utils/os_unix.c
g++ -c -pipe -Wformat-truncation=0 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DCONFIG_CTRL_IFACE -DCONFIG_CTRL_IFACE_UNIX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I.. -I../wpa_supplicant/src -I../wpa_supplicant/src/utils -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I.moc -isystem /usr/include/libdrm -I.ui -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/main.o main.cpp
g++: error: unrecognized command line option ‘-Wformat-truncation=0’; did you mean ‘-Wline-truncation’?
make[1]: *** [Makefile.Release:470: .obj/main.o] Error 1
make[1]: Leaving directory '~/Downloads/wpa-cute-0.7.1/src'
make: *** [Makefile:38: release] Error 2
[user@user]$ make-qt5

My OS is Hyperbola/Gnu-Linux-Libre

I don't suppose you could tell me how to fix this for my own use, idk maybe fix this issue?
What requirements does this application have btw? Does it require anything specfic?

Besides the packages mentioned here: https://aur.archlinux.org/packages/wpa-cute/

**Comment by FrostKnight** [comment]
ps, this error happens in every version after 8.0 even the master janurary build.

Not sure about the other versions but yeah.

**Comment by loh-tar** [comment]
> I don't suppose you could tell me how to fix this for my own use,

Yeah, no idea, sorry.
You need to search for this one. 

> unrecognized command line option ‘-Wformat-truncation=0’

I did it but without a quick hit.
Something special at your distro? May ask there.
Bad gcc version?

> What requirements does this application have btw? Does it require anything specfic?

So far I remember not, no. All what is of interest should be mentioned in the docs.

Good luck!

**Comment by FrostKnight** [comment]
Hmm.. so it has to do with GCC? I wonder... what version of gcc do i need to use this?

**Comment by loh-tar** [comment]
No idea what version is needed. My gcc says now 9.1, and the man page knows the format-truncation option.

greppiing my Make file use it too:
```
$ grep truncation Makefile.Release 
CXXFLAGS      = -pipe -Wformat-truncation=0 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
        g++ -pipe -Wformat-truncation=0 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -W -dM -E -o .moc/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp
```

You may rebuild the Makefile without these option (ask the web how to do it) or just edit the file. 

Qt 5.8 sounds a little outdated, but quess is not the issue here.

**Comment by FrostKnight** [comment]
hmmm... that does help me compile it, now I just need to figure out why I cannot connect to anything...
;)

It may be some error I am unaware of. But yeah, at least this issue is solved.
