### ISSUE TITLE
Add WPA3 support

### ISSUE THREAD

**Issue by 0xDED** [loh-tar/wpa-cute#8]
According to [this](https://wiki.archlinux.org/index.php/Network_configuration/Wireless#WPA3_Personal) wpa_supplicant supports WPA3.
However, wpa-cute currently does not provide the option to add a WPA3 network.
Adding support for WPA3 would, in my opinion, be a great enhancement.

**Comment by loh-tar** [comment]
Sure, it should be added ASAP.
But can't say when I will look at it. Patches are welcome!

**Comment by carbolymer** [comment]
Any chances to get wpa3?

**Comment by loh-tar** [comment]
How time flies, four years already :-/
Have looked at my router. Yes, chances are not too bad :-) Ask again in two weeks if nothing happens here

**Comment by loh-tar** [comment]
Everyone is invited to try out the new wpa3 branch. Please try a lot to find and report problems. I have not yet tried wps, for example.

If someone uses WPA(2/3) Enterprise, I would be grateful for information on what is absolutely necessary or can be omitted. Or in other words, what differences there are (must be) between the two in the gui.

**Comment by loh-tar** [comment]
No one who wanted to give it a try? Not very motivating...
Well, there is a new version  with this stuff and some more.

**Comment by carbolymer** [comment]
Sorry, just got to take a look at it. WPA3 works fine, thank you very much!
